typedef enum {
	tSyntaxError = -1,				/* -1 */
	tIdent,						/* 0 */
	tStringL,					/* 1 */
	tIntegerL,					/* 2 */
	tLT,						/* 3 */
	tLE,						/* 4 */
	tLSFT,						/* 5 */
	tOPENX,						/* 6 */
	tGT,						/* 7 */
	tGE,						/* 8 */
	tRSFT,						/* 9 */
	tASSIGN,					/* 10 */
	tEQ,						/* 11 */
	tNEQ,						/* 12 */
	tIS,						/* 13 */
	tBOR,						/* 14 */
	tROR,						/* 15 */
	tBAND,						/* 16 */
	tRAND,						/* 17 */
	tSemicolon,					/* 18 */
	tMinus,						/* 19 */
	tPlus,						/* 20 */
	tABSENT,					/* 21 */
	tANY,						/* 22 */
	tAPPLICATION,					/* 23 */
	tAUTOMATIC,					/* 24 */
	tBOOLEAN,					/* 25 */
	tBEGIN,						/* 26 */
	tBIG,						/* 27 */
	tBIT,						/* 28 */
	tBY,						/* 29 */
	tCOMPONENT,					/* 30 */
	tCOMPONENTS,					/* 31 */
	tCONTAINING,					/* 32 */
	tDEFAULT,					/* 33 */
	tDEFINED,					/* 34 */
	tDEFINITIONS,					/* 35 */
	tENCODED,					/* 36 */
	tEND,						/* 37 */
	tEXPLICIT,					/* 38 */
	tEXPORTS,					/* 39 */
	tEXTENSIBILITY,					/* 40 */
	tEXTERNAL,					/* 41 */
	tFALSE,						/* 42 */
	tFROM,						/* 43 */
	tGeneralizedTime,				/* 44 */
	tIAString,					/* 45 */
	tIDENTIFIER,					/* 46 */
	tIMPLICIT,					/* 47 */
	tIMPLIED,					/* 48 */
	tIMPORTS,					/* 49 */
	tINCLUDE,					/* 50 */
	tINCLUDES,					/* 51 */
	tINTEGER,					/* 52 */
	tMINUSINFINITY,					/* 53 */
	tNULL,						/* 54 */
	tOCTET,						/* 55 */
	tOBJECT,					/* 56 */
	tOF,						/* 57 */
	tOPTIONAL,					/* 58 */
	tPRESENT,					/* 59 */
	tPLUSINFINITY,					/* 60 */
	tPRIVATE,					/* 61 */
	tREAL,						/* 62 */
	tSEQUENCE,					/* 63 */
	tSET,						/* 64 */
	tSIZE,						/* 65 */
	tSTRING,					/* 66 */
	tTAGS,						/* 67 */
	tTRUE,						/* 68 */
	tUNIVERSAL,					/* 69 */
	tUTCTime,					/* 70 */
	tVisibleString,					/* 71 */
	tWITH,						/* 72 */
	tNewLine,					/* 73 */
	tEndOfFile,					/* 74 */
	tIllegal,					/* 75 */
} InputToken;
