input:
	tSyntaxError = -1
	tLT		    '<'
	tGT	    	'>'
	tASSIGN		'='
	tEQ		    '=='
	tNEQ		'!='
	tIS		    ':='
	tSemicolon	';'

    % keywords
	tBOOLEAN	'BOOLEAN'
	tBEGIN		'BEGIN'
	tBIG		'BIG'
    tBIT        'BIT'
    tDEFINITIONS 	'DEFINITIONS'
    tEND        'END'
    tEXPLICIT   'EXPLICIT'
    tEXPORTS    'EXPORTS'
    tIMPLICIT    'IMPLICIT'
    tIMPORTS    'IMPORTS'
    tINCLUDES   'INCLUDES'
    tINTEGER    'INTEGER'
    tNULL       'NULL'
    tOCTET      'OCTET'
    tOF         'OF'
    tSEQUENCE   'SEQUENCE'
    tSTRING		'STRING'
	tREAL		'REAL'
	tSET		'SET'
	tANY		'ANY'
	tSIZE		'SIZE'
	tEXTERNAL	'EXTERNAL'
	tFROM		'FROM'
	tOBJECT		'OBJECT'
	tWITH		'WITH'
	tIDENTIFIER	'IDENTIFIER'
	tCOMPONENT	'COMPONENT'
	tOPTIONAL	'OPTIONAL'
	tPRESENT	'PRESENT'
	tDEFAULT	'DEFAULT'
	tABSENT		'ABSENT'
	tCOMPONENTS	'COMPONENTS'
	tDEFINED	'DEFINED'
	tUNIVERSAL	'UNIVERSAL'
	tBY		    'BY'
	tAPPLICATION	'APPLICATION'
	tPLUSINFINITY	'PLUSINFINITY'
	tPRIVATE	'PRIVATE'
	tMINUSINFINITY	'MINUSINFINITY'
	tTRUE		'TRUE'
	tTAGS		'TAGS'
	tFALSE		'FALSE'
	tAUTOMATIC	'AUTOMATIC'
	tEXTENSIBILITY	'EXTENSIBILITY'
	tIMPLIED	'IMPLIED'
	tENCODED	'ENCODED'
	tCONTAINING	'CONTAINING'
	tVisibleString	'VisibleString'
	tUTCTime	'UTCTime'
	tGeneralizedTime	'GeneralizedTime'
	tIAString	'IAString'
	tINCLUDE	'INCLUDE'

	tIdent		'ident'
	tStringL	'stringL'
	tIntegerL	'integerL'
	tNewLine	'<NL>'
	tEndOfFile	'<EOF>'
	;

output:
	aOutputToken;

error:
	eFirstUserError = 10
	eSslStackOverflow = 40
	;

%type Type:
%	;

%mechanism Mechanism
%	;

rules

Program:
   {[
       | tIdent :
                tDEFINITIONS
                tEND
        | tEndOfFile:
            >
   ]};

end
